_BASE_: "../Base_det.yaml"

MODEL:
  WEIGHTS: "pretrained/tt_vitaev2-s_finetune_synth-tt-mlt-13-15-textocr.pth"
  TRANSFORMER:
    VOC_SIZE: 107
    CUSTOM_DICT: 'custom_dict.txt'
  ViTAEv2:
    DROP_PATH_RATE: 0.2

DATASETS:
  TRAIN: ("vintext_train", "vintext_val")
  TEST: ("vintext_test",)

SOLVER:
  IMS_PER_BATCH: 2
  # IMAGES_PER_BATCH_TEST: 2
  BASE_LR: 1e-5
  LR_BACKBONE: 1e-5
  WARMUP_ITERS: 0
  STEPS: (100000,)
  MAX_ITER: 20000
  CHECKPOINT_PERIOD: 2000

INPUT:
  HFLIP_TRAIN: False
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640)
  MAX_SIZE_TRAIN: 1200
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TEST: 1892
  CROP:
    ENABLED: True
    CROP_INSTANCE: False
    SIZE: [0.1, 0.1]
  FORMAT: "RGB"

TEST:
  EVAL_PERIOD: 2000

OUTPUT_DIR: "output/vitaev2_s/150k_tt_mlt_13_15_textocr/finetune/vintext"